//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrylooProject.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GrylooProject.Resx.AppResources.es", typeof(AppResources_es).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        internal static string candidature {
            get {
                return ResourceManager.GetString("candidature", resourceCulture);
            }
        }
        
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        internal static string changePostalCode {
            get {
                return ResourceManager.GetString("changePostalCode", resourceCulture);
            }
        }
        
        internal static string checkInternet {
            get {
                return ResourceManager.GetString("checkInternet", resourceCulture);
            }
        }
        
        internal static string configure {
            get {
                return ResourceManager.GetString("configure", resourceCulture);
            }
        }
        
        internal static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnAlreadyhveAccnt {
            get {
                return ResourceManager.GetString("CreateNwAccnAlreadyhveAccnt", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnDOB {
            get {
                return ResourceManager.GetString("CreateNwAccnDOB", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnFemale {
            get {
                return ResourceManager.GetString("CreateNwAccnFemale", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnGender {
            get {
                return ResourceManager.GetString("CreateNwAccnGender", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnMale {
            get {
                return ResourceManager.GetString("CreateNwAccnMale", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnNextButton {
            get {
                return ResourceManager.GetString("CreateNwAccnNextButton", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnPhone {
            get {
                return ResourceManager.GetString("CreateNwAccnPhone", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnPostalCode {
            get {
                return ResourceManager.GetString("CreateNwAccnPostalCode", resourceCulture);
            }
        }
        
        internal static string CreateNwAccnTitle {
            get {
                return ResourceManager.GetString("CreateNwAccnTitle", resourceCulture);
            }
        }
        
        internal static string CreateVerificationTitle {
            get {
                return ResourceManager.GetString("CreateVerificationTitle", resourceCulture);
            }
        }
        
        internal static string EdProfileChangeButton {
            get {
                return ResourceManager.GetString("EdProfileChangeButton", resourceCulture);
            }
        }
        
        internal static string enterMobile {
            get {
                return ResourceManager.GetString("enterMobile", resourceCulture);
            }
        }
        
        internal static string enterMobileNumber {
            get {
                return ResourceManager.GetString("enterMobileNumber", resourceCulture);
            }
        }
        
        internal static string entervalidpostalcode {
            get {
                return ResourceManager.GetString("entervalidpostalcode", resourceCulture);
            }
        }
        
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        internal static string leaders {
            get {
                return ResourceManager.GetString("leaders", resourceCulture);
            }
        }
        
        internal static string legal {
            get {
                return ResourceManager.GetString("legal", resourceCulture);
            }
        }
        
        internal static string LegalNotes {
            get {
                return ResourceManager.GetString("LegalNotes", resourceCulture);
            }
        }
        
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        internal static string LoginCreateAccn {
            get {
                return ResourceManager.GetString("LoginCreateAccn", resourceCulture);
            }
        }
        
        internal static string LoginDOB {
            get {
                return ResourceManager.GetString("LoginDOB", resourceCulture);
            }
        }
        
        internal static string loginfirst {
            get {
                return ResourceManager.GetString("loginfirst", resourceCulture);
            }
        }
        
        internal static string LoginGuest {
            get {
                return ResourceManager.GetString("LoginGuest", resourceCulture);
            }
        }
        
        internal static string LogInMobile {
            get {
                return ResourceManager.GetString("LogInMobile", resourceCulture);
            }
        }
        
        internal static string makePremimum {
            get {
                return ResourceManager.GetString("makePremimum", resourceCulture);
            }
        }
        
        internal static string Myprofile {
            get {
                return ResourceManager.GetString("Myprofile", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string payNow {
            get {
                return ResourceManager.GetString("payNow", resourceCulture);
            }
        }
        
        internal static string pleaseselectgender {
            get {
                return ResourceManager.GetString("pleaseselectgender", resourceCulture);
            }
        }
        
        internal static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        internal static string postalcodefivedigit {
            get {
                return ResourceManager.GetString("postalcodefivedigit", resourceCulture);
            }
        }
        
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        internal static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        internal static string rateLeader {
            get {
                return ResourceManager.GetString("rateLeader", resourceCulture);
            }
        }
        
        internal static string RateLeaderButton {
            get {
                return ResourceManager.GetString("RateLeaderButton", resourceCulture);
            }
        }
        
        internal static string registrationPreview {
            get {
                return ResourceManager.GetString("registrationPreview", resourceCulture);
            }
        }
        
        internal static string resend {
            get {
                return ResourceManager.GetString("resend", resourceCulture);
            }
        }
        
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        internal static string selectBirthYear {
            get {
                return ResourceManager.GetString("selectBirthYear", resourceCulture);
            }
        }
        
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        internal static string ShareApp {
            get {
                return ResourceManager.GetString("ShareApp", resourceCulture);
            }
        }
        
        internal static string thereIsNoData {
            get {
                return ResourceManager.GetString("thereIsNoData", resourceCulture);
            }
        }
        
        internal static string validPostalCode {
            get {
                return ResourceManager.GetString("validPostalCode", resourceCulture);
            }
        }
        
        internal static string VerificationButton {
            get {
                return ResourceManager.GetString("VerificationButton", resourceCulture);
            }
        }
        
        internal static string VoteCandidature {
            get {
                return ResourceManager.GetString("VoteCandidature", resourceCulture);
            }
        }
        
        internal static string wouldYouLikeRate {
            get {
                return ResourceManager.GetString("wouldYouLikeRate", resourceCulture);
            }
        }
        
        internal static string wouldYouLikeVote {
            get {
                return ResourceManager.GetString("wouldYouLikeVote", resourceCulture);
            }
        }
        
        internal static string writeComment {
            get {
                return ResourceManager.GetString("writeComment", resourceCulture);
            }
        }
        
        internal static string yearOfBirth {
            get {
                return ResourceManager.GetString("yearOfBirth", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string youhavenotvote {
            get {
                return ResourceManager.GetString("youhavenotvote", resourceCulture);
            }
        }
        
        internal static string youRatedSucessfull {
            get {
                return ResourceManager.GetString("youRatedSucessfull", resourceCulture);
            }
        }
        
        internal static string yourMobileNumberMustbe {
            get {
                return ResourceManager.GetString("yourMobileNumberMustbe", resourceCulture);
            }
        }
        
        internal static string yourPostalCodeMust {
            get {
                return ResourceManager.GetString("yourPostalCodeMust", resourceCulture);
            }
        }
        
        internal static string yourSession {
            get {
                return ResourceManager.GetString("yourSession", resourceCulture);
            }
        }
        
        internal static string youVoted {
            get {
                return ResourceManager.GetString("youVoted", resourceCulture);
            }
        }
        
        internal static string alreadypremimum {
            get {
                return ResourceManager.GetString("alreadypremimum", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        internal static string notGetOtp {
            get {
                return ResourceManager.GetString("notGetOtp", resourceCulture);
            }
        }
        
        internal static string stripeGetway {
            get {
                return ResourceManager.GetString("stripeGetway", resourceCulture);
            }
        }
        
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        internal static string pricePackage {
            get {
                return ResourceManager.GetString("pricePackage", resourceCulture);
            }
        }
        
        internal static string selectType {
            get {
                return ResourceManager.GetString("selectType", resourceCulture);
            }
        }
        
        internal static string lastsevendays {
            get {
                return ResourceManager.GetString("lastsevendays", resourceCulture);
            }
        }
        
        internal static string lastfiftendays {
            get {
                return ResourceManager.GetString("lastfiftendays", resourceCulture);
            }
        }
        
        internal static string lastthirtyndays {
            get {
                return ResourceManager.GetString("lastthirtyndays", resourceCulture);
            }
        }
        
        internal static string lastsixtydays {
            get {
                return ResourceManager.GetString("lastsixtydays", resourceCulture);
            }
        }
        
        internal static string lastoneyeardays {
            get {
                return ResourceManager.GetString("lastoneyeardays", resourceCulture);
            }
        }
        
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        internal static string totalCountry {
            get {
                return ResourceManager.GetString("totalCountry", resourceCulture);
            }
        }
        
        internal static string totalregion {
            get {
                return ResourceManager.GetString("totalregion", resourceCulture);
            }
        }
        
        internal static string selectTime {
            get {
                return ResourceManager.GetString("selectTime", resourceCulture);
            }
        }
        
        internal static string lastsixmonth {
            get {
                return ResourceManager.GetString("lastsixmonth", resourceCulture);
            }
        }
        
        internal static string lasttwomonth {
            get {
                return ResourceManager.GetString("lasttwomonth", resourceCulture);
            }
        }
        
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        internal static string cardNumber {
            get {
                return ResourceManager.GetString("cardNumber", resourceCulture);
            }
        }
        
        internal static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        internal static string entercard {
            get {
                return ResourceManager.GetString("entercard", resourceCulture);
            }
        }
        
        internal static string entercomment {
            get {
                return ResourceManager.GetString("entercomment", resourceCulture);
            }
        }
        
        internal static string entercvv {
            get {
                return ResourceManager.GetString("entercvv", resourceCulture);
            }
        }
        
        internal static string entermonth {
            get {
                return ResourceManager.GetString("entermonth", resourceCulture);
            }
        }
        
        internal static string entervalidcard {
            get {
                return ResourceManager.GetString("entervalidcard", resourceCulture);
            }
        }
        
        internal static string entervalidcvv {
            get {
                return ResourceManager.GetString("entervalidcvv", resourceCulture);
            }
        }
        
        internal static string entervalidmonth {
            get {
                return ResourceManager.GetString("entervalidmonth", resourceCulture);
            }
        }
        
        internal static string entervalidyear {
            get {
                return ResourceManager.GetString("entervalidyear", resourceCulture);
            }
        }
        
        internal static string enteryear {
            get {
                return ResourceManager.GetString("enteryear", resourceCulture);
            }
        }
        
        internal static string fora {
            get {
                return ResourceManager.GetString("fora", resourceCulture);
            }
        }
        
        internal static string monthLicence {
            get {
                return ResourceManager.GetString("monthLicence", resourceCulture);
            }
        }
        
        internal static string newPostalcode {
            get {
                return ResourceManager.GetString("newPostalcode", resourceCulture);
            }
        }
        
        internal static string PaymentSuccessful {
            get {
                return ResourceManager.GetString("PaymentSuccessful", resourceCulture);
            }
        }
        
        internal static string Pleasebecomepremimumuser {
            get {
                return ResourceManager.GetString("Pleasebecomepremimumuser", resourceCulture);
            }
        }
        
        internal static string pMonth {
            get {
                return ResourceManager.GetString("pMonth", resourceCulture);
            }
        }
        
        internal static string Postalcodeupdated {
            get {
                return ResourceManager.GetString("Postalcodeupdated", resourceCulture);
            }
        }
        
        internal static string pYear {
            get {
                return ResourceManager.GetString("pYear", resourceCulture);
            }
        }
        
        internal static string Sucess {
            get {
                return ResourceManager.GetString("Sucess", resourceCulture);
            }
        }
        
        internal static string Thischartisnotvisible {
            get {
                return ResourceManager.GetString("Thischartisnotvisible", resourceCulture);
            }
        }
        
        internal static string chartEight {
            get {
                return ResourceManager.GetString("chartEight", resourceCulture);
            }
        }
        
        internal static string chartFive {
            get {
                return ResourceManager.GetString("chartFive", resourceCulture);
            }
        }
        
        internal static string chartFour {
            get {
                return ResourceManager.GetString("chartFour", resourceCulture);
            }
        }
        
        internal static string chartNine {
            get {
                return ResourceManager.GetString("chartNine", resourceCulture);
            }
        }
        
        internal static string chartOne {
            get {
                return ResourceManager.GetString("chartOne", resourceCulture);
            }
        }
        
        internal static string chartSeven {
            get {
                return ResourceManager.GetString("chartSeven", resourceCulture);
            }
        }
        
        internal static string chartSix {
            get {
                return ResourceManager.GetString("chartSix", resourceCulture);
            }
        }
        
        internal static string chartThree {
            get {
                return ResourceManager.GetString("chartThree", resourceCulture);
            }
        }
        
        internal static string chartTwo {
            get {
                return ResourceManager.GetString("chartTwo", resourceCulture);
            }
        }
        
        internal static string chartten {
            get {
                return ResourceManager.GetString("chartten", resourceCulture);
            }
        }
        
        internal static string chartelaven {
            get {
                return ResourceManager.GetString("chartelaven", resourceCulture);
            }
        }
        
        internal static string chartetwalav {
            get {
                return ResourceManager.GetString("chartetwalav", resourceCulture);
            }
        }
        
        internal static string chartethirteen {
            get {
                return ResourceManager.GetString("chartethirteen", resourceCulture);
            }
        }
        
        internal static string alreadyVote {
            get {
                return ResourceManager.GetString("alreadyVote", resourceCulture);
            }
        }
        
        internal static string alreadyRate {
            get {
                return ResourceManager.GetString("alreadyRate", resourceCulture);
            }
        }
        
        internal static string ConfirmRegistration {
            get {
                return ResourceManager.GetString("ConfirmRegistration", resourceCulture);
            }
        }
        
        internal static string Updatedetails {
            get {
                return ResourceManager.GetString("Updatedetails", resourceCulture);
            }
        }
    }
}
